config/routes.rb
Ticketee::Application.routes.draw do


  devise_for :users, :controllers => { :registrations => "registrations"}
  get '/awaiting_confirmation',
      :to => "users#confirmation",
      :as => 'confirm_user'

  root :to => "projects#index"

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
      :to => 'admin/permissions#update',
      :as => :update_user_permissions

  resources :files
end

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "application" %>
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
        <%=yield(:title) %>
        <% else %>
        Ticketee
        <% end %>
    </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
  <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
      <% end %>
  <%= admins_only do %>
      <%= link_to "Admin", admin_root_path %><br>
  <% end %>
</nav>

<% flash.each do |key, value| %>
    <div class="flash" id="<%= key%>">
      <%= value %>
    </div>
<% end %>
<h1><%= link_to "Ticketee", root_path %></h1>
<%= yield %>
</body>
</html>